language: php
php:
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install

script:
  - phpunit --coverage-clover=coverage.clover --bootstrap=./vendor/autoload.php tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  fast_finish: true
  allow_failures:
    - php:
      - nightly

notifications:
    irc:
        channels:
            # This must be encrypted or forks & PRs start spamming
            # travis encrypt "ircs://irc.freenode.net:6697/#wildphp-dev" -r WildPHP/module-linksniffer
            -  secure: "oB+kt1ZjuhTMk9DnoL5JezWrhpAGiguZKoKn+66sj4CW6FcQotxl97wUJF5IJy3jUtMmFjaBgdfUhyyDlleCgZNDKYFz3edWMo5aXLnodO0FVUkoR36NcHt7sE+SJF4/Er53pyWlt443R4GpdAbE2kSI8D3mDsaF0E5MeJjffj5FAT1oE1FtTRH8x2o+Co8d7hUFLq5RkhsSYAkeokog/ljEXaKNPqmxOKiFqkimmpI4+Zf7ToNA3uJHxelNc8iLRKO2Ee/PjrYqSeA9oT3ONLQV2alzHVycbVOkGuGG2gpDHthSV9wTuuYAtyoQcb/IOLpwzzwHxKnEXkOv+vUg/WFsK7KQ9rl+jqPIm5ocHDYXWPHWZo+5kjZ4Jx81U6PZBJqjjQfwhpwcIrKISqvLIb6DfClP0wp71My3DZ3UkDK/sX6xmkmbbBprPIJ6HOJC2o5+yV3t5evplOemDPttWPZ6mfwM2ujS8SGNZiO7EbrUYh5zazsg9VshOHY3JL+5a0aeKI8j2TzOQqfJQmfyt8CFn9jK1gZ1smPwqc8XrOdTw7005SRwgwUZRDZ+1VF8cpQpvq3ZqpWTFzay1QAK7dwz7d+sVDOOr51QIA/EKbQJkec5PuDTyBPlAMHDhXe1q/nVvSpgEDL7kkfnXhWOQ81nUvIUeVyCE8IV66gZv60="
        use_notice: true
        skip_join: false
